### PR TITLE
the color palette is fixed

### PR DESCRIPTION
**Pull request by belannabarnes**
The color palette is now fixed to the top of the page when moved. Did we want the words "color palette" to move as well? also, did we want to keep the background of the palette container transparent since the grid is behind it, or change it to a different color since some of the colors might be hard to see on top of the colored grid?
Capture
Capture

### CODE REVIEW

**Review by Programmer026 — APPROVED** [review]
I feel like it would be best to change the background of the palette. I'm also not sure if there is a need for the "color palette" at the top since its fixed at the top or maybe we would have to move the "color palette" to inside the holder.

**Comment by belannabarnes** [comment]
moved "color palette" into the box and changed the background color
Capture
Capture

**Review by Programmer026 — APPROVED** [review]
Looks good to me!

**Review by anamatasanch — COMMENTED** [review]
Maybe it would be better if there was no border around the palette and if the edges were rounded. Would it look good if you tried making the background of the palette not completely opaque?

**Comment by belannabarnes** [comment]
something like this?
Capture
Capture

we could also thin the border and make it less opaque as well, like this:
Capture
Capture

**Comment by anamatasanch** [comment]
This looks amazing!!!

**Review by anamatasanch — APPROVED** [review]

**Pull request merged**
