### PR TITLE
Update all the html and css design as well as clean up code

### PR DESCRIPTION
**Pull request by thuavu**
- Renamed generateGridTest.html to generateGrid.html
- Update both generateGrid.html and game.html backgrounds
- Update scrollbar to be more aesthetically pleasing
- Did some extra code clean up

ColorByNumberTest

### CODE REVIEW

**Comment by thuavu** [comment]
Note, the music currently only plays on the menu page and not the game area. There's still a bug for that in the generateGrid.html and the game.html that does not allow the music to play.

**Review by belannabarnes — APPROVED** [review]
*chefs kiss* awesome job!

**Comment by anamatasanch** [comment]
I think the purple matched better. I will make pixelateMenu match the original menu color scheme and style

**Review by anamatasanch — CHANGES_REQUESTED** [review]
I think the purple was a better match to the background. I will fix pixelateMenu to match the color and style of the menu :)

**Comment by thuavu** [comment]
@anamatasanch It looks kind of dark originally though. The game sort of needs to feel brighter somehow. I'm open to trying other colors that go with it

**Comment by anamatasanch** [comment]
I liked the look of these two:

#E59187 ->
#E59187

#FFB473 -> 
#FFB473

**Comment by thuavu** [comment]
I love the first one! The 2nd sort of blends on the bottom, but the pink adds contrast.

**Comment by anamatasanch** [comment]
Let's do pink 😀

**Comment by thuavu** [comment]
Yeah! :)

**Comment by thuavu** [comment]
Are you pushing or should I?

**Comment by anamatasanch** [comment]
Push the menu then I'll create another pull request for the pixelateMenu restyle

**Comment by thuavu** [comment]
Pushed!

**Review by anamatasanch — APPROVED** [review]

**Pull request merged**
